name: Trigger Python Application Workflow

on:
  issue_comment:
    types: [created]
  
jobs:
  rerun-tests-job:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'run workflow')
    steps:
      - name: Trigger Python Application Workflow
        uses: ./.github/workflows/python-app.yml
        with:
          branch: ${{ github.event.issue.pull_request.head.ref }} 