name: Trigger Python Application Workflow

on:
  issue_comment:
    types: [created]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    if: > 
      ${{ github.event.issue.pull_request && github.event.comment.body == 'RUN_TESTS' }}

    steps:
      - name: Trigger Python Application Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = 'python-app.yml';
            const ref = context.payload.issue.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow,
              ref: ref
            });

            # console.log(`Triggered workflow: ${workflow} on ref: ${ref}`);
