name: Trigger Python Application Workflow

on:
  issue_comment:
    types: [created]
  
jobs:
  rerun-tests-job:
    if: contains(github.event.comment.body, 'run workflow')
    uses: ./.github/workflows/python-app.yml