# This workflow will install Python dependencies, run tests, lint, and execute tests on BrowserStack

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest browserstack-sdk
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Lint with flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Set up BrowserStack environment
    - name: BrowserStack Env Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    # Step 6: Start BrowserStack Local Tunnel
    - name: Start BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: browserstack-local-id

    # Step 7: Test with pytest on BrowserStack
    - name: Test with pytest on BrowserStack
      run: |
        cd android
        browserstack-sdk pytest -s -v *.py

    # Step 8: Stop BrowserStack Local Tunnel
    - name: Stop BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop
