name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # Step 3: Install dependencies using Pipenv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    # Step 4: Lint with flake8
    - name: Lint with flake8
      run: |
        # Run flake8 for code linting
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Set up BrowserStack environment
    - name: BrowserStack Env Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: 'BUILD_INFO'
        project-name: 'REPO_NAME'

    # Step 6: Start BrowserStack Local Tunnel
    - name: Start BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: browserstack-local-id

    # Step 7: Run tests with pytest using pytest.ini
    - name: Run tests with pytest on BrowserStack
      run: |
        cd android
        BROWSERSTACK_BUILD_NAME="Android Release Build" \
        BROWSERSTACK_PROJECT_NAME="Android Release Regression Testing" \
        BROWSERSTACK_LOG_LEVEL="debug" \
        BROWSERSTACK_TEST_OBSERVABILITY="true" \
        BROWSERSTACK_APP="./WikipediaSample.apk" \
        BROWSERSTACK_BUILD_IDENTIFIER="#${{ github.run_number }}" \
        BROWSERSTACK_PARALLELS_PER_PLATFORM="1" \
        BROWSERSTACK_LOCAL="false" \
        BROWSERSTACK_LOCAL_IDENTIFIER="" \
        BROWSERSTACK_RERUN_TESTS="false" \
        BROWSERSTACK_AUTOMATION="true" \
        pipenv run browserstack-sdk pytest --log-file=pytest_log.txt --log-cli-level=ERROR

    # Step 8: Stop BrowserStack Local Tunnel
    - name: Stop BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop
